### PR TITLE
Update kinto.ahk : bug fix and vscode improvement

### PR DESCRIPTION
**Pull request by HADMARINE**
1. Bugfix of https://github.com/rbreaves/kinto/issues/481
2. Improvement on vscode of : ALT + UpArrow / ALT + DownArrow

### CODE REVIEW

**Comment by rbreaves** [comment]
Closing I have resolved the issue directly on master. Thank you for pointing out these issues.

semicolons removed and the logic to not apply this to code editors.
```
; Go up or down a page
#IfWinNotActive ahk_group editors
    $!Down::Send {PgDn}
    $!Up::Send {PgUp}
#If
```

**Comment by rbreaves** [comment]
If you feel there are still relevant additions I should pull then please submit another PR, but try not to send one that removes all or as many of the semicolons as you had removed. I am not in a position to do all of the required testing btwn switching modes with a change like that. (If the semicolons are off in certain ways it can throw off the toggling batch file that uses perl to uncomment and recomment those lines)

I need to rewrite it, but it is what it is atm.

**Comment by HADMARINE** [comment]
Oh, I did'nt know that the semicolons are removed. I'll create new PR soon.

**Comment by HADMARINE** [comment]
I checked on my local windows 11 that the bug was fixed and new feature are working properly. Thanks

**Pull request closed without merging**
