### PR TITLE
Merge of PRs 490, 499, 536, 541, 594, 595 (renamed branch)

### PR DESCRIPTION
**Pull request by RedBearAK**
Just renamed the branch from "patch-29" to "merged_kintopy_patches". 

Merge of PRs for ease of install until they get merged with master: 

#490 - Firefox private window with Cmd+Shift+N
#499 - Fixes for media keys on arrows and numpad nav keys in GTK apps
#536 - Add Cmd+Opt+Left/Right for browser tab nav
#541 - Add Cmd+Shift+Braces for tab nav in file managers, fix SpaceFM tab nav
#594 - Updates to Finder Mods; tab nav, back/forward, normalize folder view shortcuts
#595 - Quit Chromes with Cmd+Q (Resolved conflict with master)

### CODE REVIEW

**Comment by rbreaves** [comment]
I'll try and slow down and take a look at these some time this coming week, not sure if I will merge them together or separately just yet.

**Comment by rbreaves** [comment]
This is now in conflict after latest merge.
https://github.com/rbreaves/kinto/pull/594

**Comment by RedBearAK** [comment]
@rbreaves 

That conflict comes from #506 which you just closed without merging. The code block dedicated to Chrome needed to be moved above the "general" browser code block in order to be able to override the Ctrl+Q shortcut. Just like with file managers and other things, the general case needs to be at the end, or no individual shortcut remapped in the general case can be fixed for an individual app. 

This one, #537, is just a merge of the PRs listed in the title, for my own convenience. I think I'll just go ahead and close this. Merging the individual PRs from the title should resolve any issues. 

You haven't commented on #506 yet so I'm not sure why you closed it.

**Comment by rbreaves** [comment]
@RedBearAK Oh? Well I saw 506 mentioned in the title so I assumed it was part of this larger PR that I went ahead and merged. I reviewed it and it looked ok, and figured if it'd kill several smaller birds at once I'd just go ahead and merge it instead. Saying I should roll this back out of master and merge them individually instead?

I am surprised there is any conflict really as a branch or PR that is a true merge of all those PRs ought to result in identical changes, unless something else got layered in that that steps on the toes of some other chunk of code in odd ways. Why I typically make use of cherry pick, to make sure if I branch off and want already committed code in the new branch then I just pick out the specific commits I want to carry over vs doing things by hand or the git patch method even. I feel like it is a bad habit to rewrite or copy code that was already created versus using git to relocate, restore or rollback code (more of an issue for collaboration in dev vs production environments that need to have good up time).

**Comment by rbreaves** [comment]
I did realize that this was more for your personal use, but it looked good to me & if you use these things enough to group them then I assume they are more tested to some extent as well.

**Comment by RedBearAK** [comment]
@rbreaves 

Everything is quite thoroughly tested, I've been using it all for months. Well, except for the Finder Mods updates, which were just finalized and tested. The only conflict is the re-ordering of the web browser code blocks vs the existing `kinto.py` in master. That conflict exists here only because this branch includes #506. Once #506 is resolved and accepted by you, this merge will have no conflicts.

**Comment by RedBearAK** [comment]
Reopening to edit.

**Comment by rbreaves** [comment]
I believe I already merged the 506 fix, so I don't think there is anything to resolve really on master. (I applied the fix on my hotfix branch then merged that to master and pushed it a few hours ago.)

**Comment by RedBearAK** [comment]
> I believe I already merged the 506 fix, so I don't think there is anything to resolve really on master. (I applied the fix on my hotfix branch then merged that to master and pushed it a few hours ago.)
> 

@rbreaves 

Remaining change from 506 is the reason I did the re-ordering of the browser block in the first place: Being able to quit Chrome(s) with Cmd+Q. I've added this to PR 595 after re-basing on current master's web browser block ordering. Should no longer be any conflict.

**Comment by RedBearAK** [comment]
@rbreaves 

Looks like this is pretty much all taken care of in the individual PRs, except #595. Not much reason to keep messing with this merged branch. I think I won't be opening this again.

**Pull request closed without merging**
