### PR TITLE
Installer fixes for Ubuntu, Manjaro, Lubuntu, openSUSE Tumbleweed, etc. 

### PR DESCRIPTION
**Pull request by RedBearAK**

### CODE REVIEW

**Comment by RedBearAK** [comment]
This is just a merge of some of my branches. I was actually trying to merge these into the main branch on my own fork. Closing this PR.

**Comment by RedBearAK** [comment]
Replacing older PRs with this merged version that I'm now using for general testing. All new edits will go into this "merged-1" branch.

**Comment by rbreaves** [comment]
In the future try and keep your PRs in separate and smaller PRs by making use of multiple branches per feature that you are focusing on. Typically you do this for 2 reasons imo, the code review can go faster, and if one of the PRs are rejected it won't hold up the others.

Installer fixes and Finder mods ought to be at least 2 separate PRs, typically, but I will go through it and and see what I can do.

**Comment by RedBearAK** [comment]
@rbreaves 

Yeah, sorry about that. That's exactly what I was afraid of when I created the merge. I'm still having a hard time understanding how to use git efficiently. I just barely stumbled into how to make a merged branch for testing and then I started editing the merged branch while testing more ISO images, so the older branches are now outdated. 

I can certainly separate out the Finder mods and reopen the original PR for that. 

One of the tricky things is that I'm wanting to test on systems that don't yet have git installed, so to make sure that the installer script successfully installs git as part of the process I download a ZIP from GitHub that already contains all the changes I'm attempting to test. Right now that's the "merged-1" branch.

**Comment by RedBearAK** [comment]
@rbreaves 

I'm fairly certain that I didn't do it the "right" way but I tried to put the `kinto.py` in this PR back to stock (but for some reason it's showing the new brace lines you just merged from PR #440 as "new"). Oh, silly me, all I have to do is remove them. 

Moved the modified contents of `kinto.py` back into the Finder mods PR and reopened it.

**Comment by RedBearAK** [comment]
@rbreaves 

OK, so now there are only the two files changed in this PR, the installer script and the package script.

**Comment by CyberkidAdithya** [comment]
Hello Good People, I am a CS student from India currently looking for some interesting Python Open Source Projects to work on. so, if you don't mind, will you guys let me also contribute to this project? I am good in Python, Tkinter and many other modules in Python.

**Comment by rbreaves** [comment]
Unrelated note - and I am not sure how github handles commits and all that in the web ui, but if you take the time to learn it via the terminal any you will find that there's a few very useful features that will help you minify your number of commits greatly.

Amend your commit to the previous commit
```
git commit --amend
```

Force push changes to the forked github repo - if you have already pushed the changes before the amend
```
git push -f
```

There is also a ```git rebase -i``` feature that allows for interactive rebasing but that is a little dangerous imo and may not be wise for a beginner, however it does all for they call squashing where you can also minify your commits and then do a force push to the server.

An easier route might be to do a ```get reset --soft HEAD~10``` and replace 10 with however many commits back you want to go and that will relocate your "head" back to whatever commit was X commits ago and --soft will keep your changes intact locally. You can then follow it up with a ```git add .``` to add all files or ```git add -u``` to only add modified files & not entirely new files. After that your files will be staged and ready for either a normal commit ```git commit -m "Your commit decription here"``` or you can do another ```git commit --amend```.

Just thought I'd mention that, I know there's a lot I have not mentioned, such as ```git checkout branchName```, and pull or fetch, but most of those are covered in basic tutorials out there or the first 5 minutes of any git tutorial on youtube. The other practical stuff though sometimes gets glossed over or is only brought up in  a 30m long beginners tutorial, if at all. Once I slow down I probably should do a practical video guide to git to be honest lol - the one I would have appreciated a decade ago.

**Comment by rbreaves** [comment]
@CyberkidAdithya I'd be happy to have you on board! Just fork the project, if you haven't already. And you can either go through the issue tickets or find something of your own that you'd like to add or think is missing. Just try and keep any Pull Requests to 1 feature at a time, create individual branches on your fork as needed of course.

**Comment by RedBearAK** [comment]
@rbreaves 

I pulled the SELinux related patches from this (PR #437, installer fixes) so there shouldn't be any real conflicts if you first merge the fixes from @prosac that allows Fedora to stay in enforcing mode. That was a much better solution. 

The Finder mods contain a single code block so it was easy to just replace it with a new PR with a single commit. But this one... uhhh... I'm working on it. Trying to see if I can easily pull out parts that are unrelated to other sections and put them in separate PRs. I did manage to merge everything into my own master branch so at this point I can completely disassemble this if I have to.

**Comment by RedBearAK** [comment]
Closing this because it's just too much of a mess, and turned out to be mostly unnecessary.

**Pull request closed without merging**
