### PR TITLE
Adding support for sysvinit & mxlinux w/ xfce

### PR DESCRIPTION
**Pull request by rbreaves**

### CODE REVIEW

**Comment by rbreaves** [comment]
@RedBearAK You will probably like this, even though it is specific to MX Linux I imagine it will be applicable to any sysvinit based distro.

**Comment by RedBearAK** [comment]
@rbreaves 

Nice. I did ultimately ditch MX for Mint on that old 2002 Pentium 4 laptop. With the same type of performance tuning I applied to MX, Mint 19.3 (the last 32-bit version) ended up running just as well as MX with 1GB and 2GB RAM, but felt more "modern" and friendly. 

But I remember the problem with lack of `sysvinit` support. If this will add support for many of the distros and users that have resisted `systemd`, that's excellent.

**Comment by rbreaves** [comment]
I'm so limited on space with the Dell Mini 9, only 8gb of space I don't think I could fit Linux Mint on there lol. I think I will spin that up in a VM though.

**Comment by RedBearAK** [comment]
>I'm so limited on space with the Dell Mini 9, only 8gb of space I don't think I could fit Linux Mint on there lol. I think I will spin that up in a VM though.

Yeah, that's the one thing I was wondering when I said that, if MX still has the advantage on install size over Mint for such a small drive. Probably. But I had added like a 128GB mSATA SSD in an IDE adapter case in that ancient P4 laptop, so disk space wasn't really an issue. 

I really wasted a ridiculous amount of time playing with that old thing. But I learned a lot along the way.

**Comment by rbreaves** [comment]
Oh wow.. I also ordered that same type of adapter, but sadly it had to go straight to a PCI-E type interface and the adapter did not convert mSata over to being a PATA IDE type interface which is the only interface my dell BIOS understands on that PCIE slot :/.

**Comment by RedBearAK** [comment]
I couldn’t immediately understand why you were talking about PATA, but I found this. 

> The problem is that Dell custom-wired the connector. It is a MiniPCIe in form factor, but MiniPCIe normally has SATA, not PATA. Dell used the connector for PATA and then designed a custom SSD for it.

Wow, what a pain. Nice little machines always seem to have some artificially created glitch like that. Eww. 

Oh, wait now I remember. Mine was actually an mSATA to SATA 2.5 case, then into a SATA-to-PATA adapter that turned the optical drive bay into a SATA hard drive bay. LOL. I do also have mSATA to IDE cases for use in the bay where the hard drive was originally installed. But in the HDD bay I usually had an IDE to CF card adapter that made it much easier to boot from and install different distros, because I couldn’t get much of anything to boot in the optical drive. They’re a little expensive but a fast CompactFlash card is a good HDD replacement on really old IDE systems. I was thinking of putting one in a gumdrop iMac at one point.

**Comment by rbreaves** [comment]
Well that was a bigger update than I expected it to be.. I believe I have it sorted but I will be doing more testing with it tomorrow before merging it. It does seem to be installing properly though on sysvinit and systemd now.

**Comment by rbreaves** [comment]
Merging these changes into dev, the changes appear to be stable and I got rid of a number of deprecation errors and warnings with kinto-gui.py. I think I will add the ability to checkout any custom branch from kinto via a parameter in kairos though.

**Comment by RedBearAK** [comment]
@rbreaves 

The deprecation errors do seem to be gone. But I'm not getting good results trying to install the dev branch (downloaded manually as a ZIP) on a fresh MX install. 

Xfce Whisker Menu still blocking the Super_L key (Win key), so I can't get through the installer GUI without changing it. 

Service does not activate. I'm seeing errors in the GUI window like `tail: cannot open '/tmp/kinto.log' for reading: no such file or directory`. And in the terminal, if I'm running the GUI from the therminal, I see `sudo: /etc/init.d/kinto: command not found`. 

Then when closing the GUI window, I see this in the terminal: `gi.repository.GLib.Error: g-invoke-error-quark: Class __main__+MyWindow doesn't implement delete_event (1)`. 

Right at the end of the install script output I already see this, same as above: 

`sudo: /etc/init.d/kinto: command not found`

This is using the default boot option, non-systemd. So looks like the init file for Kinto is not being successfully installed? Just guessing at this point.

**Comment by rbreaves** [comment]
Oh, well true.. the work of checking out any OS level conflicts hasn't actually been performed just yet and I am sorta aware of there being some issue(s) there lol - but really that's inline with what I would expected of an XFCE based distro & I just need to update the logic for that..

After this quick clean up though - and making another few minor additions to Kairos I do plan to start the process of rewriting the installer for Kinto a bit to simplify the mess that it is in terms of other people adding support for additional distros. Just adding this one for me took a good bit of effort, but that was largely due to sysvinit and comparatively systemd distros would be relatively simple.

I may also start accepting more PRs before I do the rewrite of the installer. I want to make sure I don't lose any contributions in this process.

**Comment by RedBearAK** [comment]
> It ought to just run at this point lol.

Ah, yes, the infamous, "It really should be working," strikes again. Let me know if I can run some commands or something to help troubleshoot. I can keep reverting my VM back to the "just installed and updated" snapshot as many times as needed.

**Comment by rbreaves** [comment]
Sorry about that.. it should be working now, unlike systemd the start, stop, restart and status commands work differently now. I don't have a real status function, although I could easily add that, it is basically just tail -f /tmp/kinto.log.

I had forgot to copy the kinto service file over into the /etc/init.d/ directory and also the removal of it as well.. that has now been added.

As far as start and stop it is this for sysvinit.

```
sudo -E /etc/init.d/kinto start
sudo -E /etc/init.d/kinto stop
```

**Comment by RedBearAK** [comment]
Looks like it is working, but I've only tested it so far in the VM without reverting to the clean snapshot. Figured that would be faster than redownloading all the packages, in case it hits another glitch. But it does seem to be working now, even after a restart. 

I forgot that when Alt+Tab breaks in a new Xfce system that's actually a good sign. After I manually changed it to Ctrl+Backslash and set the Whisker Menu shortcut to Alt+F1 (have to disable Kinto and press the physical Alt+F1 keys to do that, it's one of the ones that can't be set when Kinto is enabled), then everything is working as expected.  Browsers, file manager, terminal, all behaving normally. 

So I will proceed to testing in a clean VM reverted to a pre-Kinto snapshot. Maybe my internet was slower in the middle of the day, but that initial attempted install took quite a while. 

But, are you seeing all of this stuff from the screenshots below in the GUI window whenever you restart the service via the GUI menu? Or are you only (re)starting the service via the terminal? (Trying terminal commands...) I guess it shows up in the terminal for me too. Maybe specific to being in a GNOME Box? 

gui_log1

gui_log2

**Comment by rbreaves** [comment]
Yea, some of the dependencies can take a little while to bring down, I think mx linux in particular needed a few additional dependencies that most other distros already have so that is probably why it felt like it took longer.. it did lol. Overall it is probably like an extra 20-30mb if that. MX Linux is definitely the lightest OS I have added support for, beating out even Enso OS.

**Comment by RedBearAK** [comment]
I think it's the servers being very slow for some reason. It's downloading about 48MB of packages but taking more than 20 minutes to do it. 

Anyway, got through it with a clean VM and it seems to be working great. Also after a restart. 

Nice work.

**Comment by rbreaves** [comment]
Thanks for testing it, I will probably make a release some time tomorrow and increment to 1.2-9 after that, the basis for sysvinit support is there now. And I will try and make a few more xfce related tweaks as well. There may even be some xfce related PRs or tickets outstanding too that need merging/adding.

**Comment by rbreaves** [comment]
Hotkeys for xfce w/ whiskermenu are now fixed in dev if you want to give it another spin. Will be merging into master today. @RedBearAK

More logic for detecting the launcher being used needs to be added - but I think I am just going to launch w/ it this way for now.. Although I probably should grab the value associated with Super_L and use whatever that happens to be for Alt-F1.. I might fix this before merging actually.

**Comment by RedBearAK** [comment]
Sounds excellent. Will test ASAP. 

... Nope. [Zoidberg] "Your fix is bad, and you should feel bad!" [/Zoidberg] 

Whisker Menu now has two entries, so still blocking Super_L from the installer GUI. Should be an easy fix though. Just make sure you delete the existing shortcut entry while replacing it. 

Screenshot: 

double_whiskers

**Comment by RedBearAK** [comment]
But of course  once I deleted the extraneous Super_L shortcut the install completes and the Cmd+Space shortcut opens the menu as expected. And Alt+Tab is working right away. 

That's about all that was ever going wrong with installing in Xfce, if I remember right. So after fixing the duplicate shortcut it should be all good in Xfce from now on. 

The Debian update servers that MX is using seem hella faster this morning. The Kinto install took like 3 minutes in a clean VM this time. Seems a little soon but maybe they already repaired the undersea cable that was damaged a week ago and took down our internet for nearly a whole day.

**Comment by rbreaves** [comment]
Hmm... I am working from a macbook, hence why I do not run into that installer issue. I can disable the Super key during the installer phase easily enough and then re-enable that hotkey. I want both entries otherwise when users stop the service their actual super key will not work and to be honest - I should re-enable it for gnome as well after the installer phase.

**Comment by RedBearAK** [comment]
OK, so whatever you did now puts Alt+Tab and Shift+Alt+Tab in the category of shortcuts that can't be set properly under Kinto by pressing those physical keys. 

If I try to set the "Cycle windows" shortcut to physical Alt+Tab under Kinto, I wind up with just "Control R". Even if I try to use the Win key as Alt, it winds up as just "Alt L". Same for "Reverse cycle windows" but just with Shift added. 

I suppose it should never actually matter if it works properly in the background, but it's just weird. 

> Hmm... I am working from a macbook, hence why I do not run into that installer issue. I can disable the Super key during the installer phase easily enough and then re-enable that hotkey. I want both entries otherwise when users stop the service their actual super key will not work and to be honest - I should re-enable it for gnome as well after the installer phase.

Oh, dear. 

If your goal is to have as little impact as possible on the existing shortcuts, I guess it makes sense to leave it alone outside of the installation phase. But if your goal is more to mimic macOS as much as possible, I would point out that the Command key on macOS, just like all other "modifier" keys, has never been set up to perform an action on its own just because you failed to press another key before releasing it. Modifier keys, by definition, are supposed to modify something else. So I have always considered it "safe" to press and release a modifier key like Shift or Command without performing a full shortcut combination, because I know nothing will happen. 

The idea of using the system meta key alone to open menus or the Activity Overview is a Linux/Windows thing, and feels very alien and annoying after 20 years of macOS. I've always liked that Kinto usually fixes that, except in KDE which requires editing a text file and restarting `kwin`. 

At the very least I would wish for a tweak option to disable letting the system meta key operating by itself, even if you don't want to make that the default behavior anymore. 

I use Albert in most DEs (even KDE where I still prefer it to `krunner`) to help mimic the quick application launching and file search access I have in macOS, so an ideal solution would be to have a choice between changing the system key from using Cmd to Cmd+Space, but alternately allowing it to be changed to something like Cmd+Shift+Space to allow Cmd+Space to be dedicated to some other launcher like Albert. I have `krunner` on Alt+Space (physical Win+Space). 

That's my two cents on the matter.

**Comment by RedBearAK** [comment]
Here's the last thing that I forgot for Xfce, that I would probably ever care about getting fixed: "Switch window for same application" is set by default to Super+Tab. Other shortcuts I'm trying to set while Kinto is active are also coming out weird, ignoring the additional key and just registering the modifier. 

But this one I can at least set to Alt+Grave by using Win+Grave while Kinto is active, and then it works as expected to cycle an application's windows. I didn't need to modify `kinto.py` this time to get it to stop operating as "Reverse cycle windows". 

If I remember right, I used to have to set RC+Grave == RC+Grave to fix that. But that might have been just to get it to work consistently across Xfce, Cinnamon and MATE on Mint. Been a while since I've been using Mint regularly. 

So I guess you'd want to actually make Kinto work with "Switch window for same application" by making it compatible with the existing Super+Tab shortcut, rather than changing the shortcut, the same way you did with Alt+Tab?

**Comment by rbreaves** [comment]
I don't really feel like switching within app category to be important to getting this specific PR merged. That can be separate and may already have a ticket out there for all I know. As things stand now I appear to have the Super key conflict during install resolved.

**Comment by RedBearAK** [comment]
Well, I just thought since you did the other main Xfce shortcuts already, and it's fresh in your mind how to do it, that this would be a good time to fix that last drop in the Xfce bucket. Not essential, certainly. But there is probably no ticket specific to that since I never created one, and who else would? LOL. If you want it separate I'll have to make one. 

Will test dev branch on MX again ASAP and let you know.

**Comment by rbreaves** [comment]
@RedBearAK Oh.. I misunderstood what you were talking about - thought you wanted switch within same application to be implemented or asked of the user vs normal Alt-Tab. Yea.. I do see now.. it is creating a conflict. Will resolve. Thanks.

**Comment by RedBearAK** [comment]
No, just the normal Cmd+Grave "within application" window cycling stuff. Not "application switching", if that's what you mean. (Weirdly, Xfce has a shortcut for that but I can't really understand how it's different from the regular cycle windows thing, except maybe that it doesn't bring up the switcher dialog.)

Anyway, having some trouble with the latest dev branch. 

Gets through the installer without blocking... no duplicate shortcut showing for Super_L... 

Terminal asks for "any key" to set the shortcut back to Super_L. Which I did not notice for a while, because I was messing with the GUI and other windows. Went back and hit "any key" in the terminal, then the duplicate shortcut entry re-appears... 

OK, so the tray icon goes white as soon as the GUI process is completed, as if Kinto is active and working, but it doesn't actually start mapping until I return to the terminal and press "any key" to get entirely through the installer. Sooo... it's kind of awkward. 

Normally once the GUI window comes up I don't have to pay any attention to what's happening in the terminal anymore. So I wasn't. I was trying to Cmd+Q out of the GUI window (which often requires doing Alt+Tab at least once and then coming back to the GUI window before it will work), and trying other types of windows, and was confused for a few minutes why nothing was working. 

Technically, once you go back and respond to the terminal asking for "any key", it works. But this process is different from before, and could be confusing for some users. Seems like the GUI was unable to view the log or restart the service from the menu prior to completing the install in the terminal, as if the service file was not copied into place yet at that point. What if the user closes the terminal window (ignoring the warning about a running process) and kills the install process prematurely after the GUI window comes up? I'm guessing that would leave the install in a broken state until setup is run again.

**Comment by rbreaves** [comment]
Well I took that back out the remapping of Super because for some reason I thought I was or could ignore it the same way I do for Windows - but xkeysnail does not work that way and I forgot. Xkeysnail can ignore combos - not an entire modifier key like Super when pressed alone.

So that prompt is no longer thing - if I want to restore the Super key then that needs to be part of the system tray & gui app and occur after the process itself ends and then undo it again when the process starts.. may delay that addition for later.

The Ctrl-Tab stuff ought to work now, Super-Tab entries are removed via a new sed command in dev.

**Comment by RedBearAK** [comment]
I see the delay and I'm totally fine with it. Been kind of wanting to ask for a bit of a delay anyway. I've been noticing at least in Neon that sometimes the service was restarting so fast that the tray icon wouldn't register and change white-black-white. So sometimes as I'm testing new lines in my config file I couldn't be certain that I'd actually restarted the service each time. A small delay would be nice. 

The "switch within application" does not appear to be working. Looking at the commit, shouldn't that be setting the custom shortcut to Ctrl+Grave, so it works on physical Alt+Grave? I don't know why you'd be referencing Ctrl+Tab for that. And it doesn't work on physical Ctrl+Tab either. Why? Don't know. 

I'm looking for it to work on physical Alt+Grave (logical Ctrl+Grave), just like Cmd+Grave on a Mac.

**Comment by rbreaves** [comment]
The switching within application is now working, I was working on that after the last commit, sorry about not making that clear. A part of me didn't want to deal with it as it wasn't working before and not important to me personally but meh.. important enough and it needs to be there so it is now if you want to test again.

@RedBearAK

**Comment by RedBearAK** [comment]
I may be having a stroke, but is this correct? The backslash? (From one of the most recent commits.) 

```
        pgrep 'bin\xkeysnail' | xargs -r -n1 sudo kill
```

Yeah, the different keyboards are confusing. 

Hey, it's working! That's the stuff! 

Shortcut is still set to Super+Tab as default, but it works on physical Alt+Grave. Nice. 

I think Xfce for the most part can be put to bed now. 

I am just running the new installer versions over the top of the existing installation. I can re-run from a clean snapshot if necessary.

**Comment by rbreaves** [comment]
Very nice catch! I did indeed need to update that to this, so I will make another update.

```
sudo pkill -f bin/xkeysnail >/dev/null 2>&1
# or
ps aux | awk '/[b]in\/xkeysnail/ {print $2}' | xargs -r -n1 sudo kill

```

**Comment by RedBearAK** [comment]
Went ahead and did it from scratch in a clean snapshot. Everything is working out of the box for me, as far as I can tell. No hitches installing, Alt+Tab and Alt+Grave working as expected (like Cmd+Tab and Cmd+Grave). Alt+Space (Cmd+Space) opens the Whisker menu, as expected. 

Don't know of any other thing I can comment on as a visible issue on my side. 

>Very nice catch!

That looks better. Backslashes are for escaping, at least I know that much. LOL. That just jumped out to my eye. It helped that it was highlighted specifically. LOL. 

Let me know if you need to run another test cycle before merging.

**Comment by rbreaves** [comment]
I've gone ahead and merged it! But I definitely appreciate you helping me out as quickly as you have been, some of these things I certainly would have missed and needed addressing! About to push the 1.2-9 release!

**Comment by RedBearAK** [comment]
No problem. Sorry to be so much trouble asking for fixes that weren't necessarily important to the main task. But now they're done, and don't need to be dealt with later. Have a beer or whatever. That was quite a big addition to the master branch, and an important one.

**Comment by rbreaves** [comment]
Thanks 😂.. and yea at the tail end of it I just wanted to get it done. I guess I was really surprised to see that I haven't made a major release in like a month.. but then again I was so busy the last couple of weeks before this one it just literally wasn't possible to make a release and I am sorta hating myself because I know there is a backlog of things I want to do on this project, Kairos and another project that Windows users would likely appreciate - but it will mostly likely be a commercial software package as it will take a good bit of time to build out and has a more definite end goal that'll not go on forever besides maintenance the OS updates may eventually require.

**Comment by rbreaves** [comment]
So finally.. I am turning my chair around and will be installing this directly on my Dell Mini 9! 😂 and I think it might have been @probonopd that had wanted me to support other system services managers besides systemd, so I guess here it is lol.

**Comment by RedBearAK** [comment]
Hey! That's neat how you put an either/or logic in the main installer link, so it works with either `wget` or `curl`. Love it. So I guess that would try `wget` first and then fall back to `curl` if that fails. Very clever. I would not have thought to do that. That takes the onus off the user to choose between two links. Really nice. 

I'm running the install again from the master link in a clean snapshot. Not expecting anything different, just making sure. 

... results as expected. Working like a charm. 

I don't think I ever asked specifically for `sysvinit` support since on MX it was easy to just reboot into using `systemd`, but I'm sure it will be appreciated by more than just me. 

Just remember not to push so hard that you stop having fun. 

Oh, one last thing, speaking of the Mini 9. It doesn't use `sysvinit`, so not relevant to this thread really, but through recent testing I noticed that Lubuntu 18.04 (the last 32-bit version) uses quite a bit less RAM (about 160MB or less vs 320MB for Xfce) and less storage space (about 4.4GB vs 6GB) than MX or other Xfce desktops do. They were still using LXDE at the time. It barely uses more RAM than IceWM. 

So Lubuntu 18.04, maybe with Albert as a spotlight replacement (because the LXDE menu doesn't have a search feature unlike pretty much all recent DE menus), could be a nice option if you actually want to do anything useful with that little machine besides play with MX. The file manager (PCManFM) is supported by my Finder mods and the LXTerminal app is in `kinto.py`, so it should be a decent experience out of the box. 

Cheers.

**Comment by rbreaves** [comment]
> I don't think I ever asked specifically for sysvinit support since on MX it was easy to just reboot into using systemd, but I'm sure it will be appreciated by more than just me.

Wait a minute.. rebooting into systemd was an option? 😂 Now someone tells me.

And yea.. MX Linux and the Ubuntu stock does not appear to have curl by default, I think you had mentioned that about Ubuntu already, so yea combining it made sense.

**Comment by rbreaves** [comment]
It does look like I need to delay kinto-gui.py from running the tail -f against the log - or add something in that waits for it to start up before trying to show the log. That minor detail can wait for later though lol. I probably will make an issue ticket so I do not forget though.

**Comment by RedBearAK** [comment]
Haha, yeah... LXDE is one of those old DEs that seemed pretty dedicated to looking like Windows 98. Funny that you would even ask them to add a global menu. LOL. But I think the UI looking so old and being stuck looking like Windows is mainly why I didn't want to use Lubuntu on that old P4 laptop, and went with Mint Xfce instead. But when your storage is that limited... 

> It does look like I need to delay kinto-gui.py from running the tail -f against the log - or add something in that waits for it to start up before trying to show the log. That minor detail can wait for later though lol. I probably will make an issue ticket so I do not forget though.

Yes, that would be good, for later. In testing, I did have to try and restart from the menu at times to see some output, but didn't really find it important as long as Kinto was activating properly.

**Comment by RedBearAK** [comment]
Just wondering, you don't have some way to have global menus working on Windows, right? I've always assumed that's not possible.

**Comment by rbreaves** [comment]
Lol, can't keep anything under wraps w/ you around lol. 😂 There's been some work on that - but that is the other project that I try not to talk about a whole lot right not because it is still kinda early but some progress has been made in that area, but there's a lot of work to be done still. And yes that lee-soft app is what made me really dig into it more. I wanted to use his codebase but it is an absolute mess and Microsoft and their APIs have changed a lot sense then, so working it from the ground up is about the only option.

**Comment by RedBearAK** [comment]
That is too dang funny. Guess I'll check back on the status of that next year. But I can certainly do some beta testing if you ever get to that point. If you can do better I'll be very interested to see it. 

Gotta go for now.

**Pull request merged**
